namespace LigaStavok.UdfsNext.Provider.BetRadar
{
    // ReSharper disable InconsistentNaming

    public enum ProductType
    {
        /// <summary>
        ///    Indicates the message was generated by the live-odds product
        /// </summary>
        LiveOdds = 1,

        /// <summary>
        ///    Indicates the message was generated by the MTS (Managed Trading Services) product
        /// </summary>
        MTS = 2,

        /// <summary>
        ///    Indicates the message was generated by the LCoO (Live Cycle of Odds) product
        /// </summary>
        LCoO = 3,

        /// <summary>
        ///    Indicates the message was generated by the BetPal
        /// </summary>
        BetPal = 4,

        /// <summary>
        ///    Indicates the message was generated by the PremiumCricket
        /// </summary>
        PremiumCricket = 5,

        /// <summary>
        ///    Indicates the message was generated by the virtual sports product
        /// </summary>
        Virtuals = 6
    }

    // ReSharper restore InconsistentNaming
}