namespace LigaStavok.UdfsNext.Provider.BetRadar.RabbitMQ.Messages
{
    public enum OddsChangeReason
    {
        /// <summary>
        ///    Indicates the message was generated by normal service execution
        /// </summary>
        Normal = 0,

        /// <summary>
        ///    Indicates the message was generated due to risk adjustment
        /// </summary>
        RiskAdjustment = 1,

        /// <summary>
        ///    Indicates the message was generated because the feed system went down
        /// </summary>
        SystemDown = 2
    }
}